# CONSTANTS for review app
SLICELENGTH = 50
MINYEAR = 1895
MIN_SCORE_VALUE = 1
MAX_SCORE_VALUE = 10
EMAIL_MAX_LENGTH = 254
USERNAME_MAX_LENGTH = 150
CONFIRMATION_CODE_MAX_LENGTH = 100
USERNAME_REGEX = r'^[\w.@+-]+\Z'
FORBIDDEN_USERNAME = 'me'
ROLE_NAME_MAX_LENGTH = 100
