# CONSTANTS for review app
MAX_SERIALIZER_SCORE = 10
MIN_SERIALIZER_SCORE = 0
SLICE_LENGTH = 50
MIN_YEAR = 1895
MIN_SCORE_VALUE = 1
MAX_SCORE_VALUE = 10
EMAIL_MAX_LENGTH = 254
USERNAME_MAX_LENGTH = 150
CONFIRMATION_CODE_MAX_LENGTH = 100
USERNAME_REGEX = r'^[\w.@+-]+\Z'
FORBIDDEN_USERNAME = 'me'
ROLE_NAME_MAX_LENGTH = 100
MODELS_NAME_LENGTH = 256
