# Generated by Django 3.2 on 2024-08-08 15:18

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_comment_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[reviews.models.real_year], verbose_name='Год выпуска'),
        ),
    ]
